version: '3.7'

services:
  web:
    build: .
    # command: python /code/manage.py runserver 0.0.0.0:8000
    command: gunicorn bookstore_project.wsgi -b 0.0.0.0:8000
    environment:
      - ENVIRONMENT=development
      - SECRET_KEY=vka%qs_!(ix*or87wri(a0g0c@&-q7@-#39a0qa#26-q9*97x_
      - DEBUG=1
      - DEFAULT_FROM_EMAIL=kehvarl@kehvarl.com
      - EMAIL_HOST=mail.test.com
      - EMAIL_HOST_USER=test
      - EMAIL_HOST_PASSWORD=test_password
      - EMAIL_PORT=25
      - EMAIL_USE_TLS=False
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
